### ISSUE TITLE
希望增加列表转导图和表格的功能

### ISSUE THREAD

**Issue by 5kyfkr** [UFDXD/HBuilderX-Light#1]
现在集市的主题半数以上都有这个功能了，用的基本都是集市里notion主题那一套的代码，所以这个属性在别的主题也能共用的，希望增加

**Comment by UFDXD** [comment]
好的

**Comment by UFDXD** [comment]
> 现在集市的主题半数以上都有这个功能了，用的基本都是集市里notion主题那一套的代码，所以这个属性在别的主题也能共用的，希望增加

好的
