### ISSUE TITLE
建议左侧文档树鼠标移上的时候不要缩进

### ISSUE THREAD

**Issue by xibaoning** [UFDXD/HBuilderX-Light#10]
如题, 来回缩进的跳动, 导致点击失误,  比如想点击箭头展开, 结果点在了图标上

**Comment by xibaoning** [comment]
如果图标不能点击,修改图标怎么处理呢

**Comment by UFDXD** [comment]
@xibaoning 最近没有空，这两天为了防止D大频繁主题改版，我没有适配主题，这个问题会在思源界面样式稳定的时候，一波适配中改进，因为主题这几次改版之前应该是没有这么大的缩进量的。

**Comment by UFDXD** [comment]
@xibaoning  https://github.com/UFDXD/HBuilderX-Light/releases/tag/HBuilderX-Light-0.2.4.4
