### ISSUE TITLE
右上角菜单简化

### ISSUE THREAD

**Issue by Tukali** [UFDXD/HBuilderX-Light#13]
右上角的菜单特别多，平时也就刚打开的时候会设置一下，是否能够参考Dark+主题只保留常用几个，其他的可以隐藏，需要的时候展开使用即可

**Comment by UFDXD** [comment]
@Tukali 这个有考虑过，不过近期没空，需要等等。

**Comment by ippreacher** [comment]
主题很棒！不过按钮确实有点多，期待隐藏一下
