### ISSUE TITLE
字体菜单不显示

### ISSUE THREAD

**Issue by xiaopingguoniuroubao** [UFDXD/HBuilderX-Light#15]
![Snipaste_2023-01-24_03-22-11](https://user-images.githubusercontent.com/97099401/214130936-2e1dd0f5-f4fb-468e-806e-75826e740982.png)

如图，更换其他主题没有出现，很喜欢这个主题

**Comment by UFDXD** [comment]
@xiaopingguoniuroubao  
![image](https://user-images.githubusercontent.com/97731736/214787317-7f423fc4-b33f-4f3f-a048-fca6530b546e.png)

好像没有什么问题，思源这个菜单还有其他我不知道的功能吗？
