### ISSUE TITLE
JS小白求救：单复制获取日期相关代码不能在其他主题生效

### ISSUE THREAD

**Issue by chenshinshi** [UFDXD/HBuilderX-Light#17]
自己很喜欢在标题下显示创建日期和母子文档的功能，将theme.js文件中的从生成标题下动态下划线到生成母子文档显示容器的相关代码复制到了自己使用的主题的js文件中，不能生效。
只能通过将整篇js文件覆盖实现。
排查时发现删除无关功能的代码也会使该功能失效。
虽然通过删除检测创建工具栏按钮的方式遮蔽了不需要的功能，凑凑合合可以用了（）。

**Comment by UFDXD** [comment]
@chenshinshi  可能功能代码的依赖api没有一起复制出来。我将一些可能会复用的代码还有思源api抽离、封装到them,js文件较下方。
![image](https://user-images.githubusercontent.com/97731736/224595586-1e62e63f-77bc-4577-a72f-cfe0e65fbee6.png)
![image](https://user-images.githubusercontent.com/97731736/224595595-a5b872ef-d56c-40ad-8fca-985589fd4876.png)
这些下面的代码会有你需要主题功能的依赖api。需要将依赖api找出来一起复制。不想找可以全复制过来不要动它（只有需要的api会被调用，无关的api不会被使用）
