### ISSUE TITLE
希望添加兼容自适应宽度？

### ISSUE THREAD

**Issue by bemofan** [UFDXD/HBuilderX-Light#4]
大佬，很喜欢这个主题，希望能够添加兼容官方设置里的自适应宽度

**Comment by UFDXD** [comment]
@bemofan 感谢你的喜欢，自适应宽度问题我知道，有空会修的

**Comment by UserZYF** [comment]
现在官方对开启自适应宽度前后的两种状态添加了不同的选择器，可以对宽度进行具体的设置；或者删除掉增加的代码，恢复默认的宽度

**Comment by UFDXD** [comment]
@UserZYF 感谢提醒

**Comment by UFDXD** [comment]
@bemofan 已经弄好了下次更新
