### ISSUE TITLE
PDF标注的背景颜色

### ISSUE THREAD

**Issue by wrwe3888** [UFDXD/HBuilderX-Light#5]
你的主题非常漂亮呀。请教：在PDF上标注的时候，选中一段文字，可以用背景颜色将其高亮，可是目前的背景颜色很深，让文字的可见度不是很好，有没有办法让标注的颜色浅一点啊？一点点背景就好。十分感谢！

**Comment by UFDXD** [comment]
@wrwe3888  
![image](https://user-images.githubusercontent.com/97731736/191895573-65e91c87-8949-454b-8ca8-34dcf1478edd.png)
这样可以吗
