### ISSUE TITLE
希望对文档的H标题进行编号显示

### ISSUE THREAD

**Issue by xibaoning** [UFDXD/HBuilderX-Light#6]
如题

**Comment by UFDXD** [comment]
@xibaoning 你好其实这个功能早就做好了，只是发现思源的动态加载和标题编号显示天然不符合。因为文章前面因动态加载消失了，那么标题编号就会重新计算。这样就不准了。所以主题才没有加进来。

**Comment by xibaoning** [comment]
可以根据左侧大纲来嘛, 大纲是有层次的, 等大纲生成后再根据这个修改H标题, 也许可以

**Comment by UFDXD** [comment]
@xibaoning 大纲是可以被关闭的，且大纲只可以显示一篇文档，并且需要考虑拖动分屏的情况。
