### ISSUE TITLE
笔记标题被遮挡

### ISSUE THREAD

**Issue by clark874** [UFDXD/HBuilderX-Light#7]
感谢作者的工作！
汇报一个笔记标题被遮挡的问题:
<img width="553" alt="image" src="https://user-images.githubusercontent.com/86122040/194930395-94b40c35-8003-4369-b918-305f1c2e04bb.png">

**Comment by UFDXD** [comment]
@clark874  面包屑应该是半透明的，看样子样式加载不完全。
请问是浏览器环境吗？若是的话，是什么浏览器。

**Comment by UFDXD** [comment]
@clark874 是win系统吗？

**Comment by UFDXD** [comment]
@UFDXD 
![image](https://user-images.githubusercontent.com/97731736/195063432-6552af18-44a1-4a75-a021-4577605579d6.png)
重置一下看看，因为我这并没有这个问题

**Comment by UFDXD** [comment]
@clark874 
![image](https://user-images.githubusercontent.com/97731736/195063833-17f9bf34-06ec-4c85-8505-6158794ad193.png)
应该是这样的半透明的

**Comment by clark874** [comment]
是MacBook，重置后仍然是不透明的


在 2022年10月11日 18:09:35, UFDXD ***@***.***) 写到:

@clark874 面包屑应该是半透明的，看样子样式加载不完全。
请问是浏览器环境吗？若是的话，是什么浏览器。

**Comment by UFDXD** [comment]
@clark874  能截个“页面元素”比较全的图吗？思源笔记用户指南>排版元素 这个文档页面里的内容就行。

**Comment by clark874** [comment]
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/86122040/195249385-15c3a8c9-ab76-489c-a3f9-2b92833920f0.png">

**Comment by clark874** [comment]
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/86122040/195249867-09984509-bb8a-4fc1-aba5-32956b9edc8f.png">
遮挡后标题上方也没有空间了，被面包屑的条挡住了

**Comment by UFDXD** [comment]
@clark874 整个theme.cs 文件都没加载啊。正常加载是这样的。
![2022-10-12_152525](https://user-images.githubusercontent.com/97731736/195278639-db94a2ee-6b45-428c-9cd5-fab223f94326.png)

**Comment by UFDXD** [comment]
@clark874 话说，你有没有手动改过主题文件。还有去掉主题滤镜后。主题theme,cs文件能正常加载吗？
![image](https://user-images.githubusercontent.com/97731736/195280945-cd0aebd9-8915-4c9c-87ef-0c14c26033b0.png)

**Comment by clark874** [comment]
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/86122040/195285278-ef9e1830-943c-46e6-80b8-69aae1fe1a6e.png">
似乎是加载失败了

**Comment by clark874** [comment]
<img width="225" alt="image" src="https://user-images.githubusercontent.com/86122040/195286432-c973c0a7-be7e-45b0-b453-d954f06bce3f.png">
在http://127.0.0.1:6806/appearance/themes/HBuilderX-Light/中没有personal这个文件夹

**Comment by clark874** [comment]
theme.js文件里这段是不是要注释掉?
<img width="776" alt="image" src="https://user-images.githubusercontent.com/86122040/195287006-d37305be-ff20-48f3-9354-e815b59cbe16.png">

**Comment by UFDXD** [comment]
@clark874  你可以试试，但大概率没关系，因为他们在theme.cs文件后面加载。这些文件是我自己用的，主题发布不会加进去的。
你把主题滤镜去除，然后重启软件，在软件启动完成后主题显示后，打开控制台将 head 标签内全部元素截图给我看，我看看theme.cs文件到底有没有被加载。
![image](https://user-images.githubusercontent.com/97731736/195333853-76083141-442b-4d4d-b209-81ba3667a24b.png)
这是正常的head 标签内全部元素。
![image](https://user-images.githubusercontent.com/97731736/195334032-7ecbd29f-c78b-436c-97ec-42029de6f924.png)
折叠状态点那个三角展开

**Comment by clark874** [comment]
<img width="951" alt="image" src="https://user-images.githubusercontent.com/86122040/195388545-e247ef7c-0bd5-499e-8ca8-6f24abf7bd09.png">
去掉了滤镜，原版显示

**Comment by clark874** [comment]
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/86122040/195388940-97aeb2d2-ab67-46ff-bebe-7412de924a9f.png">
加入滤镜后显示

**Comment by UFDXD** [comment]
@clark874  虽然不知道为什么 theme.css 文件没加载的上，滤镜css文件可以由js调用加载，那么用js加载theme.css文件就好了。
请将     loadStyle("/appearance/themes/HBuilderX-Light/theme.css", "themeStyle");
代码放入
![image](https://user-images.githubusercontent.com/97731736/195624976-3744835f-99d5-43da-ac48-947663f998e9.png)
theme.js 文件这个位置保存重启思源，看看。
若是能解决你的问题的话，下个主题版本我将这行代码就加进去了。
