### ISSUE TITLE
笔记菜单被挡住

### ISSUE THREAD

**Issue by clark874** [UFDXD/HBuilderX-Light#8]
如图，在底部右键菜单时多出程序边界的部分会被挡住。
<img width="692" alt="image" src="https://user-images.githubusercontent.com/86122040/195392636-802ac6be-6b86-4045-b4b2-a122ce06e7e3.png">

**Comment by UFDXD** [comment]
@clark874  ？？ 
这个功能能用不就好了吗？虽然实现的比较粗暴。但我自己也在用，没有进行特别像这样情况的处理优化。因为在最底下用这个功能的情况太少了吧。

**Comment by UFDXD** [comment]
@clark874 这个问题闲下来会考虑重弄一下的，现在问题我关了
